[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='0xa716a1447d9bc0f424d41b1d5145cabd5849d5c9179a5c54ecfaee12a79624dc'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
